export type CertificationAuthority =
  | "Meta"
  | "LinkedIn"
  | "Coursera"
  | "HackerRank"
  | "Duke University"
  | "DeepLearning.AI"
  | "Udemy"
  | "SoloLearn"
  | "HackerX";

export type CertificationDomain =
  | "Backend"
  | "Frontend"
  | "Mobile"
  | "Data Science"
  | "Blockchain"
  | "Security"
  | "DevOps"
  | "Languages"
  | "AI/ML"
  | "Fundamentals";

export interface Certification {
  id: string;
  name: string;
  url: string;
  authority: CertificationAuthority;
  domain: CertificationDomain;
  date: string;
  licenseNumber?: string;
  featured?: boolean;
}

export interface AuthorityInfo {
  name: CertificationAuthority;
  icon: string;
  iconLib: "si" | "custom";
  color: string;
}

export const authorities: AuthorityInfo[] = [
  { name: "Meta", icon: "SiMeta", iconLib: "si", color: "#0668E1" },
  { name: "LinkedIn", icon: "SiLinkedin", iconLib: "si", color: "#0A66C2" },
  { name: "Coursera", icon: "SiCoursera", iconLib: "si", color: "#0056D2" },
  { name: "HackerRank", icon: "SiHackerrank", iconLib: "si", color: "#00EA64" },
  { name: "Duke University", icon: "duke", iconLib: "custom", color: "#003087" },
  { name: "DeepLearning.AI", icon: "SiOpenai", iconLib: "si", color: "#FF6F00" },
  { name: "Udemy", icon: "SiUdemy", iconLib: "si", color: "#A435F0" },
  { name: "SoloLearn", icon: "SiSololearn", iconLib: "si", color: "#149EF2" },
  { name: "HackerX", icon: "hackerx", iconLib: "custom", color: "#FF5722" },
];

export const domains: CertificationDomain[] = [
  "Backend",
  "Frontend",
  "Mobile",
  "Data Science",
  "Blockchain",
  "Security",
  "DevOps",
  "Languages",
  "AI/ML",
  "Fundamentals",
];

export const certifications: Certification[] = [
  // Featured Meta Specializations
  {
    id: "meta-backend",
    name: "Meta Back-End Developer Specialization",
    url: "https://www.coursera.org/account/accomplishments/specialization/REKAGL94VMEA",
    authority: "Meta",
    domain: "Backend",
    date: "Feb 2024",
    licenseNumber: "REKAGL94VMEA",
    featured: true,
  },
  {
    id: "meta-android",
    name: "Android Mobile Application Development",
    url: "https://www.coursera.org/account/accomplishments/records/GC267GSS7D9Q",
    authority: "Meta",
    domain: "Mobile",
    date: "Nov 2023",
    licenseNumber: "GC267GSS7D9Q",
    featured: true,
  },
  {
    id: "meta-react-native",
    name: "React Native Development",
    url: "https://www.coursera.org/account/accomplishments/records/ZJN3UAJQTSPV",
    authority: "Meta",
    domain: "Mobile",
    date: "Jan 2024",
    licenseNumber: "ZJN3UAJQTSPV",
    featured: true,
  },
  {
    id: "meta-frontend",
    name: "Advanced React & Frontend",
    url: "https://www.coursera.org/account/accomplishments/records/SBLHCV28YSXR",
    authority: "Meta",
    domain: "Frontend",
    date: "Jan 2024",
    licenseNumber: "SBLHCV28YSXR",
    featured: true,
  },
  {
    id: "meta-database",
    name: "Introduction to Databases for Back-End Development",
    url: "https://www.coursera.org/account/accomplishments/records/7FKEVK9ALLFM",
    authority: "Meta",
    domain: "Backend",
    date: "Jan 2024",
    licenseNumber: "7FKEVK9ALLFM",
    featured: true,
  },
  // Featured University Specializations
  {
    id: "rust-duke",
    name: "Rust Programming Specialization",
    url: "https://www.coursera.org/account/accomplishments/specialization/SX8K3C18M4DX",
    authority: "Duke University",
    domain: "Languages",
    date: "Nov 2024",
    licenseNumber: "SX8K3C18M4DX",
    featured: true,
  },
  {
    id: "golang-coursera",
    name: "Programming with Google Go Specialization",
    url: "https://www.coursera.org/account/accomplishments/specialization/certificate/SXHJ9Y8S8ZQC",
    authority: "Coursera",
    domain: "Languages",
    date: "Oct 2023",
    licenseNumber: "SXHJ9Y8S8ZQC",
    featured: true,
  },
  // Featured Security
  {
    id: "cybersecurity-hackerx",
    name: "Ethical Hacking & Cybersecurity",
    url: "https://us-central1-projectx-rs2020.cloudfunctions.net/certificate/file/image/cwmScqAwZbQyS0CYBFl3b74Z2CI3/final%20certificate",
    authority: "HackerX",
    domain: "Security",
    date: "Aug 2024",
    licenseNumber: "49ca12b521",
    featured: true,
  },
  // Featured AI/ML
  {
    id: "deeplearning-tensorflow",
    name: "Introduction to TensorFlow for AI, ML, and Deep Learning",
    url: "https://www.coursera.org/account/accomplishments/records/SUUG3VDDL7M2",
    authority: "DeepLearning.AI",
    domain: "AI/ML",
    date: "Jun 2024",
    licenseNumber: "SUUG3VDDL7M2",
    featured: true,
  },
  {
    id: "deeplearning-gans",
    name: "Build Basic Generative Adversarial Networks (GANs)",
    url: "https://www.coursera.org/account/accomplishments/records/CH5UFP7FFTHT",
    authority: "DeepLearning.AI",
    domain: "AI/ML",
    date: "Jun 2024",
    licenseNumber: "CH5UFP7FFTHT",
    featured: true,
  },
  // Blockchain
  {
    id: "blockchain-spec",
    name: "BlockChain Specialization",
    url: "https://coursera.org/share/97438e4de7c4ffc5806c73d04cfbca42",
    authority: "Coursera",
    domain: "Blockchain",
    date: "Sep 2022",
    licenseNumber: "UP9B6B5Q3UMM",
  },
  {
    id: "smart-contracts",
    name: "Smart Contracts",
    url: "https://www.coursera.org/account/accomplishments/verify/A6V2PUTMX9CT",
    authority: "Coursera",
    domain: "Blockchain",
    date: "Sep 2022",
    licenseNumber: "A6V2PUTMX9CT",
  },
  {
    id: "dapps",
    name: "Decentralized Applications (Dapps)",
    url: "https://coursera.org/share/5a9f0961040c8edb4a8833a349a6049f",
    authority: "Coursera",
    domain: "Blockchain",
    date: "Sep 2022",
    licenseNumber: "AV4EZQRSMRPS",
  },
  // Meta Additional
  {
    id: "meta-django",
    name: "Django Web Framework",
    url: "https://www.coursera.org/account/accomplishments/records/PNTR4VKVUZEY",
    authority: "Meta",
    domain: "Backend",
    date: "Jan 2024",
    licenseNumber: "PNTR4VKVUZEY",
  },
  {
    id: "meta-apis",
    name: "APIs",
    url: "https://www.coursera.org/account/accomplishments/records/446KRJQB4QRZ",
    authority: "Meta",
    domain: "Backend",
    date: "Feb 2024",
    licenseNumber: "446KRJQB4QRZ",
  },
  {
    id: "meta-fullstack",
    name: "The Full Stack",
    url: "https://www.coursera.org/account/accomplishments/records/AXYXKREYRPAB",
    authority: "Meta",
    domain: "Backend",
    date: "Jan 2024",
    licenseNumber: "AXYXKREYRPAB",
  },
  {
    id: "meta-capstone",
    name: "Back-End Developer Capstone",
    url: "https://www.coursera.org/account/accomplishments/records/9E6W569YS9W4",
    authority: "Meta",
    domain: "Backend",
    date: "Feb 2024",
    licenseNumber: "9E6W569YS9W4",
  },
  {
    id: "meta-kotlin-fundamentals",
    name: "Programming Fundamentals in Kotlin",
    url: "https://www.coursera.org/account/accomplishments/records/AYX82FHWX8Z3",
    authority: "Meta",
    domain: "Mobile",
    date: "Dec 2023",
    licenseNumber: "AYX82FHWX8Z3",
  },
  {
    id: "meta-kotlin-advanced",
    name: "Advanced Programming in Kotlin",
    url: "https://www.coursera.org/account/accomplishments/records/XBPRZKAN32TB",
    authority: "Meta",
    domain: "Mobile",
    date: "Dec 2023",
    licenseNumber: "XBPRZKAN32TB",
  },
  {
    id: "meta-android-ui",
    name: "Create the User Interface in Android Studio",
    url: "https://www.coursera.org/account/accomplishments/records/Z74TJW9E5ZJF",
    authority: "Meta",
    domain: "Mobile",
    date: "Dec 2023",
    licenseNumber: "Z74TJW9E5ZJF",
  },
  {
    id: "meta-android-data",
    name: "Working with Data in Android",
    url: "https://www.coursera.org/account/accomplishments/records/LMY865L5AXA7",
    authority: "Meta",
    domain: "Mobile",
    date: "Dec 2023",
    licenseNumber: "LMY865L5AXA7",
  },
  {
    id: "meta-js-mobile",
    name: "Mobile Development and JavaScript",
    url: "https://www.coursera.org/account/accomplishments/records/T2278XBS65KS",
    authority: "Meta",
    domain: "Mobile",
    date: "Dec 2023",
    licenseNumber: "T2278XBS65KS",
  },
  {
    id: "meta-react-basics",
    name: "React Basics",
    url: "https://www.coursera.org/account/accomplishments/records/TS3HFARD93BZ",
    authority: "Meta",
    domain: "Frontend",
    date: "Jan 2024",
    licenseNumber: "TS3HFARD93BZ",
  },
  {
    id: "meta-ux-ui",
    name: "Principles of UX/UI Design",
    url: "https://www.coursera.org/account/accomplishments/records/EPMFQAMG96AM",
    authority: "Meta",
    domain: "Frontend",
    date: "Jan 2024",
    licenseNumber: "EPMFQAMG96AM",
  },
  {
    id: "meta-interview",
    name: "Coding Interview Preparation",
    url: "https://www.coursera.org/account/accomplishments/records/KSN9NKKXT372",
    authority: "Meta",
    domain: "Fundamentals",
    date: "Jan 2024",
    licenseNumber: "KSN9NKKXT372",
  },
  {
    id: "meta-backend-intro",
    name: "Introduction to Back-End Development",
    url: "https://www.coursera.org/account/accomplishments/records/Y55DZPXWVMDH",
    authority: "Meta",
    domain: "Backend",
    date: "Jan 2024",
    licenseNumber: "Y55DZPXWVMDH",
  },
  {
    id: "meta-js",
    name: "Programming with JavaScript",
    url: "https://www.coursera.org/account/accomplishments/records/UP5T4FHZ5YJL",
    authority: "Meta",
    domain: "Languages",
    date: "Jan 2024",
    licenseNumber: "UP5T4FHZ5YJL",
  },
  {
    id: "meta-python",
    name: "Programming in Python",
    url: "https://www.coursera.org/account/accomplishments/records/ATSMQKTVYQ3V",
    authority: "Meta",
    domain: "Languages",
    date: "Jan 2024",
    licenseNumber: "ATSMQKTVYQ3V",
  },
  {
    id: "meta-version-control",
    name: "Version Control",
    url: "https://www.coursera.org/account/accomplishments/records/BNFXTG2M43GJ",
    authority: "Meta",
    domain: "DevOps",
    date: "Dec 2023",
    licenseNumber: "BNFXTG2M43GJ",
  },
  // Rust from Duke
  {
    id: "rust-fundamentals",
    name: "Rust Fundamentals",
    url: "https://www.coursera.org/account/accomplishments/certificate/5MJMYSG8T9DY",
    authority: "Coursera",
    domain: "Languages",
    date: "Nov 2024",
    licenseNumber: "5MJMYSG8T9DY",
  },
  {
    id: "rust-data-eng",
    name: "Rust for Data Engineering",
    url: "https://www.coursera.org/account/accomplishments/verify/853XBVNB7EUC",
    authority: "Coursera",
    domain: "Data Science",
    date: "Nov 2024",
    licenseNumber: "853XBVNB7EUC",
  },
  {
    id: "rust-devops",
    name: "Rust for DevOps",
    url: "https://www.coursera.org/account/accomplishments/verify/W7HKH4P4ZL4L",
    authority: "Coursera",
    domain: "DevOps",
    date: "Nov 2024",
    licenseNumber: "W7HKH4P4ZL4L",
  },
  {
    id: "rust-mlops",
    name: "Rust for MLOps",
    url: "https://www.coursera.org/account/accomplishments/verify/2IN415W60IB9",
    authority: "Coursera",
    domain: "AI/ML",
    date: "Nov 2024",
    licenseNumber: "2IN415W60IB9",
  },
  {
    id: "rust-cli",
    name: "Rust & Python CLI Tooling",
    url: "https://www.coursera.org/account/accomplishments/verify/IHT8E3APD5LV",
    authority: "Coursera",
    domain: "DevOps",
    date: "Nov 2024",
    licenseNumber: "IHT8E3APD5LV",
  },
  // LinkedIn Learning
  {
    id: "linkedin-kubernetes",
    name: "Kubernetes: Microservices",
    url: "https://www.linkedin.com/learning/certificates/415bb25ccc7e2713e69fba253fb4ad04dd2c6554b080b0ef0143d80f51b9bc71",
    authority: "LinkedIn",
    domain: "DevOps",
    date: "Nov 2021",
  },
  {
    id: "linkedin-aws",
    name: "Learning Amazon Web Services (AWS) for Developers",
    url: "https://www.linkedin.com/learning/certificates/11ea88e41d070a73d22e9d75400a9ea9bc3a3c88ccd28279991db81e81c94947",
    authority: "LinkedIn",
    domain: "DevOps",
    date: "Nov 2021",
  },
  {
    id: "linkedin-angular",
    name: "Angular Essential Training",
    url: "https://www.linkedin.com/learning/certificates/64357d272519fa920d0a50202988d92fe206640e8ab4b617bdd725702e5d73f1",
    authority: "LinkedIn",
    domain: "Frontend",
    date: "Nov 2021",
  },
  {
    id: "linkedin-nodejs",
    name: "Learning Node.js",
    url: "https://www.linkedin.com/learning/certificates/590304d837b9dcb143923f0246b00e11ed64976d2998bdbd465ff3c9d7b8e902",
    authority: "LinkedIn",
    domain: "Backend",
    date: "Nov 2021",
  },
  {
    id: "linkedin-spring-angular",
    name: "Building a Reactive App with Angular and Spring Boot 2",
    url: "https://www.linkedin.com/learning/certificates/900f8839133072bc62dfddf17a6d83fc3a8827cf3008216a22b5c6e28b891989",
    authority: "LinkedIn",
    domain: "Backend",
    date: "Nov 2021",
  },
  {
    id: "linkedin-java-concurrent-1",
    name: "Parallel and Concurrent Programming with Java 1",
    url: "https://www.linkedin.com/learning/certificates/bf8703a7e6d27b4dab6e0b846d1fb621c78ddcf12c67759d0bb2d9ad3809e94d",
    authority: "LinkedIn",
    domain: "Languages",
    date: "Dec 2021",
  },
  {
    id: "linkedin-java-concurrent-2",
    name: "Parallel and Concurrent Programming with Java 2",
    url: "https://www.linkedin.com/learning/certificates/a8f2de08349d8d02c131c5b71096075523ccfad6407bfc23487a85f4355863be",
    authority: "LinkedIn",
    domain: "Languages",
    date: "Dec 2021",
  },
  {
    id: "linkedin-graphql",
    name: "Learning GraphQL",
    url: "https://www.linkedin.com/learning/certificates/5e524b301e97fd2fae939db0b98725f983cad6cc9dd889f6775e597f770eddfe",
    authority: "LinkedIn",
    domain: "Backend",
    date: "Dec 2021",
  },
  {
    id: "linkedin-java-collections",
    name: "Learning Java Collections",
    url: "https://www.linkedin.com/learning/certificates/00072b43446c54c6c0b7a274dd138dc836414d1ba2bdc993ef33559f8854dd84",
    authority: "LinkedIn",
    domain: "Languages",
    date: "Dec 2021",
  },
  {
    id: "linkedin-java-advanced",
    name: "Advanced Java Programming",
    url: "https://www.linkedin.com/learning/certificates/f82e8bfb7d502a0d55da76354da1a162a7a5cb624fd7919fd89d077a87315918",
    authority: "LinkedIn",
    domain: "Languages",
    date: "Dec 2021",
  },
  {
    id: "linkedin-spring-microservice",
    name: "Creating Your First Spring Boot Microservice",
    url: "https://www.linkedin.com/learning/certificates/81a50864133d04bc693e5674573f0d3017d708d251e066d2ecacf4d55d502f95",
    authority: "LinkedIn",
    domain: "Backend",
    date: "Dec 2021",
  },
  {
    id: "linkedin-spring-boot",
    name: "Spring Boot 2.0 Essential Training",
    url: "https://www.linkedin.com/learning/certificates/8a285ae96d8fbf81c3f01e353747dae5980bc720b55174fa26515a4d841530bc",
    authority: "LinkedIn",
    domain: "Backend",
    date: "Dec 2021",
  },
  {
    id: "linkedin-oauth",
    name: "Web Security: OAuth and OpenID Connect",
    url: "https://www.linkedin.com/learning/certificates/73ff8181c6ab7329db1faa9cad6365651e163d3b7c463f4913083632e8691aae",
    authority: "LinkedIn",
    domain: "Security",
    date: "Dec 2021",
  },
  {
    id: "linkedin-rabbitmq",
    name: "Learning RabbitMQ",
    url: "https://www.linkedin.com/learning/certificates/379391871913351850e167965776f047632666f1ef0d5ed11ff4e67455792e0a",
    authority: "LinkedIn",
    domain: "Backend",
    date: "Dec 2021",
  },
  {
    id: "linkedin-docker-microservices",
    name: "Extending, Securing, and Dockerizing Spring Boot Microservices",
    url: "https://www.linkedin.com/learning/certificates/e1d336d5cec811739da9201b97b36475688f7d22a13f7ec2bff57e721973b898",
    authority: "LinkedIn",
    domain: "DevOps",
    date: "Dec 2021",
  },
  {
    id: "linkedin-swagger",
    name: "Building APIs with Swagger and the OpenAPI Specification",
    url: "https://www.linkedin.com/learning/certificates/2f726e6e3788b6846c13a6e4b1781ab01def3ad8a87a33ac72d615444a1576db",
    authority: "LinkedIn",
    domain: "Backend",
    date: "Dec 2021",
  },
  {
    id: "linkedin-js-essential",
    name: "JavaScript Essential Training",
    url: "https://www.linkedin.com/learning/certificates/e040b4682da76e63d4006e8739c640dd30ab031a293db24a9eaec7fe57eba2b5",
    authority: "LinkedIn",
    domain: "Languages",
    date: "Dec 2021",
  },
  {
    id: "linkedin-js-tdd",
    name: "JavaScript: Test-Driven Development (ES6)",
    url: "https://www.linkedin.com/learning/certificates/d1c44dbbc034c825535d7112d0a0878fa595d965d98f32901bd450fb1183da81",
    authority: "LinkedIn",
    domain: "Languages",
    date: "Dec 2021",
  },
  {
    id: "linkedin-cypress",
    name: "End-to-End JavaScript Testing with Cypress.io",
    url: "https://www.linkedin.com/learning/certificates/67c370580728fc9e94f7dcbbcb25939c6553257e968e7388b5df201851efa35a",
    authority: "LinkedIn",
    domain: "Languages",
    date: "Dec 2021",
  },
  {
    id: "linkedin-js-security",
    name: "JavaScript: Security Essentials",
    url: "https://www.linkedin.com/learning/certificates/3323b261e8eb3a066a927dce6b00090a1a429aa4f0a8a013cae77579f91f01b6",
    authority: "LinkedIn",
    domain: "Security",
    date: "Dec 2021",
  },
  {
    id: "linkedin-ethical-hacking-js",
    name: "Ethical Hacking with JavaScript",
    url: "https://www.linkedin.com/learning/certificates/171cc52635b23ee09fd290ebb0339bbd80fe3b66466c028530e35847d80c3b2a",
    authority: "LinkedIn",
    domain: "Security",
    date: "Dec 2021",
  },
  {
    id: "linkedin-ecs",
    name: "Getting Started with ECS",
    url: "https://www.linkedin.com/learning/certificates/6914dd8dae5f254743775b1e015059199d10aef40bd33a532169e593778b21a4",
    authority: "LinkedIn",
    domain: "DevOps",
    date: "Jan 2022",
  },
  {
    id: "linkedin-react",
    name: "React.js Essential Training",
    url: "https://www.linkedin.com/learning/certificates/4dbdd2b38823bafb8ae1b36f7f3b3d2cac1c0b00159839739da07e9beaa425bd",
    authority: "LinkedIn",
    domain: "Frontend",
    date: "Jun 2022",
  },
  {
    id: "linkedin-react-fullstack",
    name: "React: Creating and Hosting a Full-Stack Site",
    url: "https://www.linkedin.com/learning/certificates/77ae2c6bc5e6de9bde7db010d87aa7a29145633b0c6dd9de01e66b90dad9400f",
    authority: "LinkedIn",
    domain: "Frontend",
    date: "Jun 2022",
  },
  {
    id: "linkedin-react-hooks",
    name: "React Hooks",
    url: "https://www.linkedin.com/learning/certificates/9a3bef81b9f88ae4ca9f1a47125ede9e59ac5629736084788185052acae6118d",
    authority: "LinkedIn",
    domain: "Frontend",
    date: "Jun 2022",
  },
  {
    id: "linkedin-node-essential",
    name: "Node.js Essential Training",
    url: "https://www.linkedin.com/learning/certificates/26158c112354225e84e5c6fef63842368986d967745ad3d9d555145b92dee8c4",
    authority: "LinkedIn",
    domain: "Backend",
    date: "Jun 2022",
  },
  {
    id: "linkedin-go-concurrency",
    name: "Applied Concurrency in Go",
    url: "https://www.linkedin.com/learning/certificates/aff91cbee2a0aa2c90e7a4fec507a6f720af3e17a6a6967b5d528ebeec16a505",
    authority: "LinkedIn",
    domain: "Languages",
    date: "Aug 2022",
  },
  {
    id: "linkedin-cpp-advanced",
    name: "C++: Advanced Topics",
    url: "https://www.linkedin.com/learning/certificates/407ade30cc38e6511fb54c18faa0d807592aa430e8363db8113fa328eda59785",
    authority: "LinkedIn",
    domain: "Languages",
    date: "Aug 2022",
  },
  {
    id: "linkedin-cpp-smart-pointers",
    name: "C++: Smart Pointers",
    url: "https://www.linkedin.com/learning/certificates/658f75d685066bdcbedd175298ff442536a19c7327af4ed2c4609f68473ec516",
    authority: "LinkedIn",
    domain: "Languages",
    date: "Apr 2018",
  },
  {
    id: "linkedin-cpp-move",
    name: "C++: Move Semantics",
    url: "https://www.linkedin.com/learning/certificates/6d01480e1e60377b2433b2dc9c225f911bd7b6574b23e2b7c4d180bad61b8800",
    authority: "LinkedIn",
    domain: "Languages",
    date: "Sep 2018",
  },
  {
    id: "linkedin-dynamic-programming",
    name: "Fundamentals of Dynamic Programming",
    url: "https://www.linkedin.com/learning/certificates/c34fc354d08c3c1f8e310d7aba96fc7a635771c9aae3fe2bc70e925c3570cd8e",
    authority: "LinkedIn",
    domain: "Fundamentals",
    date: "Nov 2021",
  },
  // HackerRank
  {
    id: "hackerrank-java-basic",
    name: "Java (Basic)",
    url: "https://www.hackerrank.com/certificates/e0aec746fa8d",
    authority: "HackerRank",
    domain: "Languages",
    date: "Sep 2020",
    licenseNumber: "EOAEC746FA8D",
  },
  {
    id: "hackerrank-java-intermediate",
    name: "Java (Intermediate)",
    url: "https://www.hackerrank.com/certificates/f3b38e8cdb26",
    authority: "HackerRank",
    domain: "Languages",
    date: "Sep 2020",
    licenseNumber: "F3B38E8CDB26",
  },
  {
    id: "hackerrank-python-basic",
    name: "Python (Basic)",
    url: "https://www.hackerrank.com/certificates/4696cf7b2a1d",
    authority: "HackerRank",
    domain: "Languages",
    date: "Sep 2020",
    licenseNumber: "4696cf7b2a1d",
  },
  {
    id: "hackerrank-python-problem-intermediate",
    name: "Python Problem Solving Skills (Intermediate)",
    url: "https://www.hackerrank.com/certificates/46669ca92fa8",
    authority: "HackerRank",
    domain: "Languages",
    date: "Sep 2020",
    licenseNumber: "46669CA92FA8",
  },
  {
    id: "hackerrank-cpp",
    name: "C++ (Basic)",
    url: "https://www.hackerrank.com/certificates/92a7f118d948",
    authority: "HackerRank",
    domain: "Languages",
    date: "Sep 2020",
    licenseNumber: "92A7F118D948",
  },
  {
    id: "hackerrank-problem-solving",
    name: "Python Problem Solving Skills (Basic)",
    url: "https://www.hackerrank.com/certificates/a141ed327f18",
    authority: "HackerRank",
    domain: "Languages",
    date: "Sep 2020",
    licenseNumber: "A141ED327F18",
  },
  // Coursera Data Science
  {
    id: "coursera-python-essentials",
    name: "Python Programming Essentials",
    url: "https://www.coursera.org/account/accomplishments/verify/JDD47ANGZEBN",
    authority: "Coursera",
    domain: "Languages",
    date: "Oct 2018",
    licenseNumber: "JDD47ANGZEBN",
  },
  {
    id: "coursera-data-science",
    name: "What is Data Science?",
    url: "https://www.coursera.org/account/accomplishments/verify/A8HM7M995NMR",
    authority: "Coursera",
    domain: "Data Science",
    date: "Oct 2018",
    licenseNumber: "A8HM7M995NMR",
  },
  {
    id: "coursera-python-data-rep",
    name: "Python Data Representations",
    url: "https://www.coursera.org/account/accomplishments/verify/5YCDGMNT5M87",
    authority: "Coursera",
    domain: "Data Science",
    date: "Oct 2018",
    licenseNumber: "5YCDGMNT5M87",
  },
  {
    id: "coursera-python-data-analysis",
    name: "Python Data Analysis",
    url: "https://www.coursera.org/account/accomplishments/verify/C8MCCHFV4HNR",
    authority: "Coursera",
    domain: "Data Science",
    date: "Oct 2018",
    licenseNumber: "C8MCCHFV4HNR",
  },
  {
    id: "coursera-java-microservices",
    name: "Building Scalable Java Microservices with Spring Boot and Spring Cloud",
    url: "https://coursera.org/verify/KMGHAC3UN39G",
    authority: "Coursera",
    domain: "Backend",
    date: "Dec 2021",
    licenseNumber: "KMGHAC3UN39G",
  },
  {
    id: "coursera-go-functional",
    name: "Go Functional Programming",
    url: "https://coursera.org/share/9bfd2d1f58cd1913a57773e80904116c",
    authority: "Coursera",
    domain: "Languages",
    date: "Oct 2023",
  },
  {
    id: "coursera-go-concurrency",
    name: "Go Concurrency",
    url: "https://www.coursera.org/account/accomplishments/verify/H9UWSLKDBAUL",
    authority: "Coursera",
    domain: "Languages",
    date: "Oct 2023",
    licenseNumber: "GYEG98A54N3U",
  },
  // Udemy
  {
    id: "udemy-8base",
    name: "8base Development",
    url: "https://ude.my/UC-00824bd5-d490-4f7f-9fdf-5b2e7d0f5899",
    authority: "Udemy",
    domain: "Backend",
    date: "Oct 2023",
    licenseNumber: "UC-00824bd5-d490-4f7f-9fdf-5b2e7d0f5899",
  },
  {
    id: "udemy-elixir-phoenix",
    name: "Elixir & Phoenix Master Bootcamp",
    url: "https://www.udemy.com/certificate/UC-501a748f-e379-49f9-9994-641113f08ea2/",
    authority: "Udemy",
    domain: "Backend",
    date: "Feb 2024",
    licenseNumber: "UC-501a748f-e379-49f9-9994-641113f08ea2",
  },
  // SoloLearn
  {
    id: "sololearn-java",
    name: "Certificate of Completion: Java Course",
    url: "http://www.sololearn.com/Profile/243342/",
    authority: "SoloLearn",
    domain: "Languages",
    date: "Aug 2015",
    licenseNumber: "1068-243342",
  },
  {
    id: "sololearn-cpp",
    name: "Certification of completion: C++ course",
    url: "http://www.sololearn.com/Profile/243342",
    authority: "SoloLearn",
    domain: "Languages",
    date: "Aug 2015",
    licenseNumber: "1051-243342",
  },
];

export const linkedInCertificationsUrl =
  "https://www.linkedin.com/in/ericgitangu/details/certifications/";

export const linkedInSkillsUrl =
  "https://www.linkedin.com/in/ericgitangu/details/skills/";
